import { Product } from './types';

const CREATED_AT = new Date('2024-01-01').toISOString();

function makeProduct(
  id: string,
  nameUk: string,
  nameEn: string,
  category: Product['category'],
): Product {
  return {
    id,
    nameUk,
    nameEn,
    category,
    tried: false,
    favorite: false,
    isCustom: false,
    createdAt: CREATED_AT,
    updatedAt: CREATED_AT,
  };
}

export const INITIAL_PRODUCTS: Product[] = [
  // Овочі та зелень (vegetables)
  makeProduct('p001', 'Авокадо', 'Avocado', 'vegetables'),
  makeProduct('p002', 'Баклажан', 'Eggplant', 'vegetables'),
  makeProduct('p003', 'Батат', 'Sweet Potato', 'vegetables'),
  makeProduct('p004', 'Броколі', 'Broccoli', 'vegetables'),
  makeProduct('p005', 'Брюссельська капуста', 'Brussels Sprouts', 'vegetables'),
  makeProduct('p006', 'Болгарський перець', 'Bell Pepper', 'vegetables'),
  makeProduct('p007', 'Буряк', 'Beetroot', 'vegetables'),
  makeProduct('p008', 'Гарбуз', 'Pumpkin', 'vegetables'),
  makeProduct('p009', 'Гриби', 'Mushrooms', 'vegetables'),
  makeProduct('p010', 'Горошок', 'Green Peas', 'vegetables'),
  makeProduct('p011', 'Еноки', 'Enoki Mushrooms', 'vegetables'),
  makeProduct('p012', 'Імбир', 'Ginger', 'vegetables'),
  makeProduct('p013', 'Кабачок', 'Zucchini', 'vegetables'),
  makeProduct('p014', 'Капуста білокачанна', 'White Cabbage', 'vegetables'),
  makeProduct('p015', 'Капуста Романеску', 'Romanesco', 'vegetables'),
  makeProduct('p016', 'Картопля', 'Potato', 'vegetables'),
  makeProduct('p017', 'Квасоля', 'Beans', 'vegetables'),
  makeProduct('p018', 'Кінза', 'Cilantro', 'vegetables'),
  makeProduct('p019', 'Кукурудза', 'Corn', 'vegetables'),
  makeProduct('p020', 'Морква', 'Carrot', 'vegetables'),
  makeProduct('p021', 'Огірок', 'Cucumber', 'vegetables'),
  makeProduct('p022', 'Пастернак', 'Parsnip', 'vegetables'),
  makeProduct('p023', 'Пекінська капуста', 'Napa Cabbage', 'vegetables'),
  makeProduct('p024', 'Петрушка', 'Parsley', 'vegetables'),
  makeProduct('p025', 'Печериці', 'Button Mushrooms', 'vegetables'),
  makeProduct('p026', 'Помідор', 'Tomato', 'vegetables'),
  makeProduct('p027', 'Редиска', 'Radish', 'vegetables'),
  makeProduct('p028', 'Редька', 'Daikon', 'vegetables'),
  makeProduct('p029', 'Рукола', 'Arugula', 'vegetables'),
  makeProduct('p030', 'Спаржа', 'Asparagus', 'vegetables'),
  makeProduct('p031', 'Стручкова квасоля', 'Green Beans', 'vegetables'),
  makeProduct('p032', 'Фенхель', 'Fennel', 'vegetables'),
  makeProduct('p033', 'Цвітна капуста', 'Cauliflower', 'vegetables'),
  makeProduct('p034', 'Цибуля', 'Onion', 'vegetables'),
  makeProduct('p035', 'Цукіні', 'Zucchini (Italian)', 'vegetables'),
  makeProduct('p036', 'Часник', 'Garlic', 'vegetables'),
  makeProduct('p037', 'Шпинат', 'Spinach', 'vegetables'),

  // Фрукти (fruits)
  makeProduct('p038', 'Абрикос/Курага', 'Apricot/Dried Apricot', 'fruits'),
  makeProduct('p039', 'Ананас', 'Pineapple', 'fruits'),
  makeProduct('p040', 'Апельсин', 'Orange', 'fruits'),
  makeProduct('p041', 'Банан', 'Banana', 'fruits'),
  makeProduct('p042', 'Виноград/Родзинки', 'Grapes/Raisins', 'fruits'),
  makeProduct('p043', 'Гранат', 'Pomegranate', 'fruits'),
  makeProduct('p044', 'Грейпфрут', 'Grapefruit', 'fruits'),
  makeProduct('p045', 'Диня', 'Melon', 'fruits'),
  makeProduct('p046', 'Кавун', 'Watermelon', 'fruits'),
  makeProduct('p047', 'Ківі', 'Kiwi', 'fruits'),
  makeProduct('p048', 'Лимон', 'Lemon', 'fruits'),
  makeProduct('p049', 'Лохіна', 'Blueberry', 'fruits'),
  makeProduct('p050', 'Малина', 'Raspberry', 'fruits'),
  makeProduct('p051', 'Мандарин', 'Mandarin', 'fruits'),
  makeProduct('p052', 'Нектарин', 'Nectarine', 'fruits'),
  makeProduct('p053', 'Ожина', 'Blackberry', 'fruits'),
  makeProduct('p054', 'Персик', 'Peach', 'fruits'),
  makeProduct('p055', 'Помело', 'Pomelo', 'fruits'),
  makeProduct('p056', 'Слива/Чорнослив', 'Plum/Prune', 'fruits'),
  makeProduct('p057', 'Смородина', 'Currant', 'fruits'),
  makeProduct('p058', 'Суниця', 'Strawberry', 'fruits'),
  makeProduct('p059', 'Фінік', 'Date', 'fruits'),
  makeProduct('p060', 'Хурма', 'Persimmon', 'fruits'),
  makeProduct('p061', 'Черешня', 'Sweet Cherry', 'fruits'),
  makeProduct('p062', 'Чорниця', 'Bilberry', 'fruits'),
  makeProduct('p063', 'Яблуко', 'Apple', 'fruits'),

  // Молочні продукти (dairy)
  makeProduct('p064', 'Вершкове масло', 'Butter', 'dairy'),
  makeProduct('p065', 'Вершковий сир', 'Cream Cheese', 'dairy'),
  makeProduct('p066', 'Вершки', 'Cream', 'dairy'),
  makeProduct('p067', 'Йогурт', 'Yogurt', 'dairy'),
  makeProduct('p068', 'Кефір', 'Kefir', 'dairy'),
  makeProduct('p069', "Молоко коров'яче", "Cow's Milk", 'dairy'),
  makeProduct('p070', 'Моцарела', 'Mozzarella', 'dairy'),
  makeProduct('p071', 'Пармезан', 'Parmesan', 'dairy'),
  makeProduct('p072', 'Ряжанка', 'Ryazhenka (Baked Milk)', 'dairy'),
  makeProduct('p073', 'Сметана', 'Sour Cream', 'dairy'),
  makeProduct('p074', 'Сир кисломолочний', 'Cottage Cheese', 'dairy'),

  // М'ясо та тваринні продукти (meat)
  makeProduct('p075', 'Індичка', 'Turkey', 'meat'),
  makeProduct('p076', 'Качка', 'Duck', 'meat'),
  makeProduct('p077', 'Кролик', 'Rabbit', 'meat'),
  makeProduct('p078', 'Печінка', 'Liver', 'meat'),
  makeProduct('p079', 'Свинина', 'Pork', 'meat'),
  makeProduct('p080', 'Серця', 'Hearts', 'meat'),
  makeProduct('p081', 'Телятина', 'Veal', 'meat'),
  makeProduct('p082', 'Язик', 'Tongue', 'meat'),
  makeProduct('p083', 'Яйце куряче', 'Chicken Egg', 'meat'),
  makeProduct('p084', 'Яйце перепелине', 'Quail Egg', 'meat'),
  makeProduct('p085', 'Яловичина', 'Beef', 'meat'),

  // Цільнозернові, крупи та бобові (grains)
  makeProduct('p086', 'Артек', 'Artek (Wheat Groats)', 'grains'),
  makeProduct('p087', 'Булгур', 'Bulgur', 'grains'),
  makeProduct('p088', 'Вівсяна каша', 'Oatmeal', 'grains'),
  makeProduct('p089', 'Гречка', 'Buckwheat', 'grains'),
  makeProduct('p090', 'Кіноа', 'Quinoa', 'grains'),
  makeProduct('p091', 'Кукурудзяна каша', 'Cornmeal Porridge', 'grains'),
  makeProduct('p092', 'Кус-кус', 'Couscous', 'grains'),
  makeProduct('p093', 'Макарони', 'Pasta', 'grains'),
  makeProduct('p094', 'Нут', 'Chickpeas', 'grains'),
  makeProduct('p095', 'Пшонка', 'Millet', 'grains'),
  makeProduct('p096', 'Рис', 'Rice', 'grains'),
  makeProduct('p097', 'Сочевиця', 'Lentils', 'grains'),
  makeProduct('p098', 'Соя', 'Soy', 'grains'),

  // Горіхи, насіння (nutsSeeds)
  makeProduct('p099', 'Арахіс', 'Peanut', 'nutsSeeds'),
  makeProduct('p100', 'Бразильський горіх', 'Brazil Nut', 'nutsSeeds'),
  makeProduct('p101', 'Гарбузове насіння', 'Pumpkin Seeds', 'nutsSeeds'),
  makeProduct('p102', 'Кедровий горіх', 'Pine Nut', 'nutsSeeds'),
  makeProduct('p103', "Кеш'ю", 'Cashew', 'nutsSeeds'),
  makeProduct('p104', 'Кокос', 'Coconut', 'nutsSeeds'),
  makeProduct('p105', 'Кунжут', 'Sesame', 'nutsSeeds'),
  makeProduct('p106', 'Мигдаль', 'Almond', 'nutsSeeds'),
  makeProduct('p107', 'Насіння льону', 'Flax Seeds', 'nutsSeeds'),
  makeProduct('p108', 'Фісташки', 'Pistachios', 'nutsSeeds'),
  makeProduct('p109', 'Фундук', 'Hazelnut', 'nutsSeeds'),
  makeProduct('p110', 'Чіа', 'Chia Seeds', 'nutsSeeds'),

  // Риба, молюски, ракоподібні (fish)
  makeProduct('p111', 'Восьминіг', 'Octopus', 'fish'),
  makeProduct('p112', 'Гребінець', 'Scallop', 'fish'),
  makeProduct('p113', 'Дорадо', 'Dorado', 'fish'),
  makeProduct('p114', 'Кальмар', 'Squid', 'fish'),
  makeProduct('p115', 'Камбала', 'Flounder', 'fish'),
  makeProduct('p116', 'Кінг-кліп', 'Kingklip', 'fish'),
  makeProduct('p117', 'Короп', 'Carp', 'fish'),
  makeProduct('p118', 'Креветки', 'Shrimp', 'fish'),
  makeProduct('p119', 'Лосось', 'Salmon', 'fish'),
  makeProduct('p120', 'Мінтай', 'Pollock', 'fish'),
  makeProduct('p121', 'Мідії', 'Mussels', 'fish'),
  makeProduct('p122', 'Окунь', 'Perch', 'fish'),
  makeProduct('p123', 'Тріска', 'Cod', 'fish'),
  makeProduct('p124', 'Тунець', 'Tuna', 'fish'),
  makeProduct('p125', 'Сібас', 'Sea Bass', 'fish'),
  makeProduct('p126', 'Форель морська', 'Sea Trout', 'fish'),

  // Спеції та олії (spices)
  makeProduct('p127', 'Базилік', 'Basil', 'spices'),
  makeProduct('p128', 'Зіра', 'Cumin', 'spices'),
  makeProduct('p129', 'Куркума', 'Turmeric', 'spices'),
  makeProduct('p130', 'Орегано', 'Oregano', 'spices'),
  makeProduct('p131', 'Паприка', 'Paprika', 'spices'),
  makeProduct('p132', 'Розмарин', 'Rosemary', 'spices'),
  makeProduct('p133', "Тим'ян", 'Thyme', 'spices'),
  makeProduct('p134', 'Кокосова олія', 'Coconut Oil', 'spices'),
  makeProduct('p135', 'Соняшникова олія', 'Sunflower Oil', 'spices'),
  makeProduct('p136', 'Гі (топлене масло)', 'Ghee', 'spices'),
  makeProduct('p137', 'Авокадова олія', 'Avocado Oil', 'spices'),
  makeProduct('p138', 'Гарбузова олія', 'Pumpkin Oil', 'spices'),
];
